language: python

python:
  - "2.7"

install:
 - "pip install -r requirements.txt"

#before_script:
script:
  - coverage run ./manage.py test
  - coverage report
  - coverage html -d cover

after_success:
  - coveralls